# Generated by Django 5.2.6 on 2026-09-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='code',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='code_promo',
        ),
    ]
