# Generated by Django 5.2.6 on 2026-09-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_retire_codes_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='moyen_paiement',
            field=models.CharField(choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('cb', 'Carte bancaire'), ('cod', 'À la livraison'), ('esp', 'Espèces en boutique')], max_length=6),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='commande',
            name='zone',
            field=models.CharField(choices=[('dakar', 'Dakar et banlieue'), ('thies', 'Thiès, Mbour'), ('regions', 'Autres régions'), ('retrait', 'Retrait en boutique')], max_length=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen',
            field=models.CharField(choices=[('wave', 'Wave'), ('om', 'Orange Money'), ('cb', 'Carte bancaire'), ('cod', 'À la livraison'), ('esp', 'Espèces en boutique')], max_length=6),
        ),
    ]
