# Generated by Django 5.2.6 on 2026-09-17 11:12

from django.db import migrations, models


def payee_devient_a_preparer(apps, schema_editor):
    """Le statut « Payée » disparaît : ces commandes étaient à préparer."""
    Commande = apps.get_model("ventes", "Commande")
    Commande.objects.filter(statut="payee").update(statut="preparation")


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_saisie_retrait_especes'),
    ]

    operations = [
        migrations.RunPython(payee_devient_a_preparer, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('preparation', 'En préparation'), ('expediee', 'En route'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=12),
        ),
    ]
