# Generated by Django 5.2.6 on 2026-10-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_sans_statut_payee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avis',
        ),
    ]
