# Generated by Django 5.2.6 on 2026-09-10 22:19

from django.db import migrations, models

# Les valeurs d'exemple livrées avec la première version. Une boutique qui les
# porte encore n'a jamais ouvert la page des réglages : on lui pose ses vraies
# coordonnées. Une boutique qui a saisi les siennes n'est pas touchée.
PLACEHOLDERS = {
    "telephone": "+221 77 000 00 00",
    "email_contact": "bonjour@mcommaman.com",
}
REELLES = {
    "telephone": "+221 76 208 02 02",
    "email_contact": "mamand202122@gmail.com",
}


def poser_les_vraies_coordonnees(apps, schema_editor):
    Reglages = apps.get_model("vitrine", "Reglages")
    for reglages in Reglages.objects.all():
        modifies = []
        for champ, exemple in PLACEHOLDERS.items():
            if getattr(reglages, champ) == exemple:
                setattr(reglages, champ, REELLES[champ])
                modifies.append(champ)
        if modifies:
            reglages.save(update_fields=modifies)


def revenir_aux_exemples(apps, schema_editor):
    """Le retour en arrière ne réécrit rien : on ne sait pas ce qui a été saisi depuis."""


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglages',
            name='email_contact',
            field=models.EmailField(default='mamand202122@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='reglages',
            name='telephone',
            field=models.CharField(default='+221 76 208 02 02', max_length=32),
        ),
        migrations.RunPython(poser_les_vraies_coordonnees, revenir_aux_exemples),
    ]
