# Generated by Django 5.2.6 on 2026-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_produit_catalogue_p_genre_5971f7_idx_and_more'),
        ('vitrine', '0002_alter_reglages_email_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglages',
            name='hero_accent',
            field=models.CharField(blank=True, default='leurs aventures.', max_length=60, verbose_name='fin du titre en couleur'),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_chapo',
            field=models.CharField(blank=True, default='Des pièces joyeuses, faciles à vivre et choisies avec le regard exigeant d’une maman.', max_length=240, verbose_name="texte d'introduction"),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_pastille',
            field=models.CharField(blank=True, default='Nouvelle collection · 2026', max_length=60, verbose_name='pastille'),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_produits',
            field=models.ManyToManyField(blank=True, help_text='Vide : les dernières nouveautés défilent', related_name='+', to='catalogue.produit', verbose_name='produits mis en avant'),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_sceau',
            field=models.CharField(blank=True, default='LIVRAISON 24 H · DAKAR ·', help_text='Le texte qui tourne autour du macaron ; vide, le macaron disparaît', max_length=60, verbose_name='texte du macaron'),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_sceau_centre',
            field=models.CharField(blank=True, default='24 h', max_length=12, verbose_name='centre du macaron'),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_sceau_legende',
            field=models.CharField(blank=True, default='chez vous', max_length=20, verbose_name='sous le centre du macaron'),
        ),
        migrations.AddField(
            model_name='reglages',
            name='hero_titre',
            field=models.CharField(default='Des looks\nqui suivent', help_text='Un retour à la ligne pour couper le titre', max_length=120, verbose_name='titre'),
        ),
    ]
