# Generated by Django 5.2.6 on 2026-09-17 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_produit_catalogue_p_genre_5971f7_idx_and_more'),
        ('vitrine', '0003_bandeau_accueil_reglable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='videotheque/%Y/%m')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('titre', models.CharField(max_length=120)),
                ('sur_accueil', models.BooleanField(default=True, verbose_name="sur l'accueil")),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('ajoutee_le', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, help_text='La pièce proposée sous la vidéo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'vidéo',
                'verbose_name_plural': 'vidéothèque',
                'ordering': ['ordre', '-ajoutee_le'],
            },
        ),
    ]
