# Generated by Django 5.2.6 on 2026-10-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_videotheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglages',
            name='hero_accent',
            field=models.CharField(blank=True, default='le coin des enfants et des mamans.', max_length=60, verbose_name='fin du titre en couleur'),
        ),
    ]
