# Generated by Django 5.2.6 on 2026-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_accueil_bienvenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglages',
            name='hero_titre',
            field=models.CharField(default='Bienvenue chez\nM comme Maman,', help_text='Un retour à la ligne pour couper le titre', max_length=120, verbose_name='titre'),
        ),
    ]
