# Generated by Django 5.2.6 on 2026-09-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='notifications_lues_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
