# Generated by Django 5.2.6 on 2026-10-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0004_notifications_lues_le'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favori',
        ),
    ]
