# Generated by Django 5.2.6 on 2026-10-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_remove_produit_catalogue_p_genre_5971f7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('prevenue_le', models.DateTimeField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='catalogue.produit')),
            ],
            options={
                'verbose_name': 'alerte de stock',
                'verbose_name_plural': 'alertes de stock',
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('produit', 'email'), name='alerte_stock_unique')],
            },
        ),
    ]
